name: Release
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2.2.0
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - id: install
      run: yarn install --frozen-lockfile
    - id: install-libs
      run: yarn install --frozen-lockfile
      working-directory: ./libs/gcp-function
    - id: prepare
      run: yarn release:prepare
      working-directory: ./libs/gcp-function
    - id: semantic-release
      run: yarn semantic-release
      working-directory: ./libs/gcp-function
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}